target_column: claim_status
split:
  test_size: 0.2
  random_state: 1889
model:
  objective: binary:logistic
  eval_metric:
  - auc
  - rmse
  - logloss
  early_stopping_rounds: 15
  enable_categorical: true
  tree_method: hist
tuning:
  n_iter: 100
  cv: 5
  scoring: roc_auc
  param_distributions:
    n_estimators:
      - 50
      - 100
      - 150
      - 200
      - 250
      - 300
      - 350
      - 400
      - 450
      - 500
    learning_rate:
      - 0.01
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.75
    subsample:
      - 0.25
      - 0.35
      - 0.45
      - 0.55
      - 0.65
      - 0.75
    max_depth:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
    colsample_bytree:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.75
    min_child_weight:
      - 1
      - 3
      - 5
      - 7
      - 9

mlflow:
  tracking_uri: http://0.0.0.0:5000/
  model_name: claim_prediction
  experiment_name: xgboost_claim_prediction
  run_name: xgboost_training_run
  register_model: true
  save_model_as: model

categorical_columns:
  - gender
  - marital_status
  - occupation
  - location
  - prev_claim_rejected
  - known_health_conditions
  - uk_residence
  - family_history_1
  - family_history_2
  - family_history_4
  - family_history_5
  - product_var_1
  - product_var_2
  - product_var_3
  - health_status
  - driving_record
  - previous_claim_rate
  - education_level
  - income_level
  - n_dependents

input_columns:
  - age
  - height_cm
  - weight_kg
  - income
  - financial_hist_1
  - financial_hist_2
  - financial_hist_3
  - financial_hist_4
  - credit_score_1
  - credit_score_2
  - credit_score_3
  - insurance_hist_1
  - insurance_hist_2
  - insurance_hist_3
  - insurance_hist_4
  - insurance_hist_5
  - bmi
  - gender
  - marital_status
  - occupation
  - location
  - prev_claim_rejected
  - known_health_conditions
  - uk_residence
  - family_history_1
  - family_history_2
  - family_history_4
  - family_history_5
  - product_var_1
  - product_var_2
  - product_var_3
  - product_var_4
  - health_status
  - driving_record
  - previous_claim_rate
  - education_level
  - income_level
  - n_dependents

prediction_output_dir: daily_predictions